services:
  tf-bounty-db:
    container_name: tf-bounty-db
    build: 
      context: ./DB
    env_file:
      - api.env
    networks:
      - tf-bounty_net
    volumes:
      - ${DB_DATA}:/var/opt/mssql

  tf-bounty-api:
    container_name: tf-bounty-api
    build: 
      context: ./
      dockerfile: api.Dockerfile
    env_file:
      - api.env
    networks:
      - tf-bounty_net
      - caddy_net

  tf-bounty-front:
    container_name: tf-bounty-front
    build: 
      context: ./
      dockerfile: blazor.Dockerfile
    env_file:
      - blazor.env
    networks:
      - tf-bounty_net
      - caddy_net

networks:
  tf-bounty_net:
    external: true
  caddy_net:
    external: true
