name: Deploy

on:
  push:
    tags: [ v* ] 
  workflow_dispatch:  # Optional: Manual trigger

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Version
        id: extract_tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Call Webhook
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}  
          API_KEY: ${{ secrets.API_KEY }}       
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "project_id": "'"$PROJECT_ID"'",
              "API_KEY": "'"$API_KEY"'",
            }' \
            "https://actions.kodevly.online/webhooks/deploy"
