name: Manual Deploy

on:
  workflow_dispatch:  

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook  
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "PROJECT_ID": "${{ secrets.PROJECT_ID }}",
              "API_KEY": "${{ secrets.API_KEY }}",
            }' \
            "https://actions.kodevly.online/webhooks/deploy \
            echo ${{ secrets.PROJECT_ID }}"
