name: Manual Deploy

on:
  workflow_dispatch:  

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}  
          API_KEY: ${{ secrets.API_KEY }}       
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "project_id": "'"$PROJECT_ID"'",
              "API_KEY": "'"$API_KEY"'",
            }' \
            "https://actions.kodevly.online/webhooks/deploy"
