name: Version-Bump
on:
  push:
    branches:
      - main  

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Cache semver-tool
        id: cache-semver
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/semver
          key: semver-tool-1.0.0

      - name: Install semver-tool (if not cached)
        if: steps.cache-semver.outputs.cache-hit != 'true'
        run: |
          curl -sLo /usr/local/bin/semver \
            https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver

      - name: Extract Bump Type from Commit Message
        id: extract_bump
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" =~ \[Version:(major|minor|patch)\] ]]; then
            echo "BUMP_TYPE=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "BUMP_TYPE=${BASH_REMATCH[1]}"
          else
            echo "No version bump requested in commit message."
            echo "SKIP_BUMP=true" >> $GITHUB_OUTPUT
            exit 78  # Skip all subsequent jobs if no version bump requested
          fi

      - name: Get Latest Tag
        needs: check-bump
        if: steps.extract_bump.outputs.SKIP_BUMP != 'true'
        id: get_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "CURRENT_VERSION=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Calculate New Version
        needs: get_tag
        id: bump_version
        run: |
          NEW_VERSION=$(semver bump ${{ steps.extract_bump.outputs.BUMP_TYPE }} ${{ steps.get_tag.outputs.CURRENT_VERSION }})
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Create and Push New Tag
        needs: bump_version
        if: steps.extract_bump.outputs.SKIP_BUMP != 'true'
        if: steps.extract_bump.outputs.BUMP_TYPE
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v${{ steps.bump_version.outputs.NEW_VERSION }}" -m "Release ${{ steps.bump_version.outputs.NEW_VERSION }}"
          git push origin "v${{ steps.bump_version.outputs.NEW_VERSION }}"
