name: Version-Bump && deploy
on:
  push:
    branches:
      - main  

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      bump_type: ${{ steps.extract_bump.outputs.BUMP_TYPE }}
      should_skip: ${{ steps.extract_bump.outputs.SKIP_BUMP }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache semver-tool
        id: cache-semver
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/semver
          key: semver-tool-1.0.0

      - name: Install semver-tool (if not cached)
        if: steps.cache-semver.outputs.cache-hit != 'true'
        run: |
          curl -sLo /usr/local/bin/semver \
            https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver

      - name: Extract Bump Type
        id: extract_bump
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" =~ \[Version:(major|minor|patch)\] ]]; then
            echo "BUMP_TYPE=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "SKIP_BUMP=true" >> $GITHUB_OUTPUT
            echo "::notice::No version bump requested"
          fi

  push-tag:
    needs: setup
    if: ${{ !needs.setup.outputs.should_skip }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache semver-tool
        id: cache-semver
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/semver
          key: semver-tool-1.0.0

      - name: Install semver-tool (if not cached)
        if: steps.cache-semver.outputs.cache-hit != 'true'
        run: |
          curl -sLo /usr/local/bin/semver \
            https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
      
      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "CURRENT_VERSION=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Calculate Version
        id: bump_version
        run: |
          NEW_VERSION=$(semver bump ${{ needs.setup.outputs.bump_type }} ${{ steps.get_tag.outputs.CURRENT_VERSION }})
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create and Push Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v${{ steps.bump_version.outputs.NEW_VERSION }}" -m "Version ${{ steps.bump_version.outputs.NEW_VERSION }}"
          git push origin "v${{ steps.bump_version.outputs.NEW_VERSION }}"

  call-webhook:
    needs: push-tag
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}  
          API_KEY: ${{ secrets.API_KEY }}       
        run: |
          curl -X POST --location 'https://actions.kodevly.online/webhooks/deploy' \
            --header 'Content-Type: application/json' \
            --data '{
              "API_KEY":"${{ secrets.API_KEY }}",
              "PROJECT_ID":"${{ secrets.PROJECT_ID }}"
            }'
